# Generated by Django 5.0.1 on 2024-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=50)),
            ],
        ),
    ]
