# Generated by Django 5.0.1 on 2024-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Action Required', 'Action Required'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=50),
        ),
    ]
